apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-ijlg87
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ijlg87
  namespace: my-nginx-ijlg87
  labels:
    name: nginx-ijlg87
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-ijlg87
  template:
    metadata:
      namespace: my-nginx-ijlg87
      labels:
        name: nginx-ijlg87
    spec:
      containers:
      - name: nginx-ijlg87
        image: nginx
        ports:
        - containerPort: 80

